const bestOffersProducts = [
  {
    id: 1,
    image: "https://picsum.photos/seed/p1/800/800",
    name: "Smart Watch Pro",
    detail: "Fitness tracking, AMOLED display",
    originalPrice: 299.99,
    discountPercent: 65,
    price: 104.99,
    link: "/product/1",
  },
  {
    id: 2,
    image: "https://picsum.photos/seed/p2/800/800",
    name: "Wireless Earbuds Plus",
    detail: "Noise canceling, 30-hour battery",
    originalPrice: 199.99,
    discountPercent: 70,
    price: 59.99,
    link: "/product/2",
  },
  {
    id: 3,
    image: "https://picsum.photos/seed/p3/800/800",
    name: "4K Webcam",
    detail: "Crystal clear video, USB plug-in",
    originalPrice: 179.99,
    discountPercent: 60,
    price: 71.99,
    link: "/product/3",
  },
  {
    id: 4,
    image: "https://picsum.photos/seed/p4/800/800",
    name: "Portable Charger 20000mAh",
    detail: "Fast charging, dual USB ports",
    originalPrice: 89.99,
    discountPercent: 55,
    price: 40.49,
    link: "/product/4",
  },
  {
    id: 5,
    image: "https://picsum.photos/seed/p5/800/800",
    name: "Mechanical Keyboard RGB",
    detail: "Tactile switches, customizable lights",
    originalPrice: 149.99,
    discountPercent: 65,
    price: 52.49,
    link: "/product/5",
  },
  {
    id: 6,
    image: "https://picsum.photos/seed/p6/800/800",
    name: "Gaming Mouse Pro",
    detail: "16000 DPI, ergonomic design",
    originalPrice: 79.99,
    discountPercent: 60,
    price: 31.99,
    link: "/product/6",
  },
  {
    id: 7,
    image: "https://picsum.photos/seed/p7/800/800",
    name: "USB-C Hub Multiport",
    detail: "7 ports, 4K HDMI support",
    originalPrice: 69.99,
    discountPercent: 55,
    price: 31.49,
    link: "/product/7",
  },
  {
    id: 8,
    image: "https://picsum.photos/seed/p8/800/800",
    name: "LED Desk Lamp Smart",
    detail: "Dimmable, color temperature control",
    originalPrice: 59.99,
    discountPercent: 65,
    price: 20.99,
    link: "/product/8",
  },
  {
    id: 9,
    image: "https://picsum.photos/seed/p9/800/800",
    name: "Bluetooth Speaker Compact",
    detail: "360-degree sound, waterproof",
    originalPrice: 89.99,
    discountPercent: 70,
    price: 26.99,
    link: "/product/9",
  },
  {
    id: 10,
    image: "https://picsum.photos/seed/p10/800/800",
    name: "Phone Stand Adjustable",
    detail: "Aluminum, universal compatibility",
    originalPrice: 49.99,
    discountPercent: 60,
    price: 19.99,
    link: "/product/10",
  },
  {
    id: 11,
    image: "https://picsum.photos/seed/p11/800/800",
    name: "Screen Protector Tempered Glass",
    detail: "Anti-glare, bubble-free installation",
    originalPrice: 29.99,
    discountPercent: 65,
    price: 10.49,
    link: "/product/11",
  },
  {
    id: 12,
    image: "https://picsum.photos/seed/p12/800/800",
    name: "Laptop Cooling Pad",
    detail: "5 fans, temperature display",
    originalPrice: 59.99,
    discountPercent: 55,
    price: 26.99,
    link: "/product/12",
  },
  {
    id: 13,
    image: "https://picsum.photos/seed/p13/800/800",
    name: "Wireless Charging Pad",
    detail: "Fast charging, LED indicator",
    originalPrice: 39.99,
    discountPercent: 70,
    price: 11.99,
    link: "/product/13",
  },
  {
    id: 14,
    image: "https://picsum.photos/seed/p14/800/800",
    name: "USB Cable Premium Quality",
    detail: "Nylon braided, 2-meter length",
    originalPrice: 19.99,
    discountPercent: 60,
    price: 7.99,
    link: "/product/14",
  },
  {
    id: 15,
    image: "https://picsum.photos/seed/p15/800/800",
    name: "Phone Case Premium",
    detail: "Shockproof, slim design",
    originalPrice: 44.99,
    discountPercent: 65,
    price: 15.74,
    link: "/product/15",
  },
  {
    id: 16,
    image: "https://picsum.photos/seed/p16/800/800",
    name: "Screen Cleaning Kit",
    detail: "Microfiber cloth, anti-static spray",
    originalPrice: 24.99,
    discountPercent: 55,
    price: 11.24,
    link: "/product/16",
  },
];

export default bestOffersProducts;
