const hotDealsProducts = [
  {
    id: 1,
    image: "https://picsum.photos/seed/hd1/800/800",
    name: "Noise Cancelling Headphones",
    detail: "Premium sound, wireless Bluetooth",
    originalPrice: 249.99,
    discountPercent: 60,
    price: 99.99,
    link: "/product/1",
  },
  {
    id: 2,
    image: "https://picsum.photos/seed/hd2/800/800",
    name: "Portable SSD 1TB",
    detail: "Ultra-fast, compact design",
    originalPrice: 179.99,
    discountPercent: 55,
    price: 80.99,
    link: "/product/2",
  },
  {
    id: 3,
    image: "https://picsum.photos/seed/hd3/800/800",
    name: "Smart Home Security Camera",
    detail: "1080p HD, night vision",
    originalPrice: 159.99,
    discountPercent: 65,
    price: 55.99,
    link: "/product/3",
  },
  {
    id: 4,
    image: "https://picsum.photos/seed/hd4/800/800",
    name: "Wireless Gaming Headset",
    detail: "7.1 surround sound, RGB",
    originalPrice: 199.99,
    discountPercent: 70,
    price: 59.99,
    link: "/product/4",
  },
  {
    id: 5,
    image: "https://picsum.photos/seed/hd5/800/800",
    name: "Tablet 10.5 inch",
    detail: "Octa-core processor, 128GB storage",
    originalPrice: 399.99,
    discountPercent: 50,
    price: 199.99,
    link: "/product/5",
  },
];

export default hotDealsProducts;
