const products2 = [
  {
    id: 1,
    image: "https://picsum.photos/seed/p201/800/800",
    name: "Laptop Stand",
    detail: "Ergonomic aluminum design",
    originalPrice: 49.99,
    discountPercent: 30,
    price: 34.99,
    link: "/product/201",
  },
  {
    id: 2,
    image: "https://picsum.photos/seed/p202/800/800",
    name: "Webcam HD",
    detail: "1080p video, auto focus",
    originalPrice: 89.99,
    discountPercent: 22,
    price: 69.99,
    link: "/product/202",
  },
  {
    id: 3,
    image: "https://picsum.photos/seed/p203/800/800",
    name: "Phone Case",
    detail: "Shockproof, slim design",
    price: 14.99,
    link: "/product/203",
  },
  {
    id: 4,
    image: "https://picsum.photos/seed/p204/800/800",
    name: "Power Bank",
    detail: "20000mAh fast charging",
    originalPrice: 59.99,
    discountPercent: 33,
    price: 39.99,
    link: "/product/204",
  },
  {
    id: 5,
    image: "https://picsum.photos/seed/p205/800/800",
    name: "Desk Lamp",
    detail: "LED, adjustable brightness",
    originalPrice: 45.0,
    discountPercent: 15,
    price: 38.25,
    link: "/product/205",
  },
  {
    id: 6,
    image: "https://picsum.photos/seed/p206/800/800",
    name: "Mouse Pad",
    detail: "XL size, smooth surface",
    price: 12.99,
    link: "/product/206",
  },
  {
    id: 7,
    image: "https://picsum.photos/seed/p207/800/800",
    name: "Cable Organizer",
    detail: "Keep desk tidy, 5-slot",
    originalPrice: 19.99,
    discountPercent: 25,
    price: 14.99,
    link: "/product/207",
  },
  {
    id: 8,
    image: "https://picsum.photos/seed/p208/800/800",
    name: "Wireless Charger",
    detail: "Fast charging, universal",
    originalPrice: 34.99,
    discountPercent: 20,
    price: 27.99,
    link: "/product/208",
  },
  {
    id: 9,
    image: "https://picsum.photos/seed/p209/800/800",
    name: "Screen Protector",
    detail: "Tempered glass, anti-glare",
    price: 9.99,
    link: "/product/209",
  },
  {
    id: 10,
    image: "https://picsum.photos/seed/p210/800/800",
    name: "Portable Fan",
    detail: "USB rechargeable, quiet",
    originalPrice: 24.99,
    discountPercent: 28,
    price: 17.99,
    link: "/product/210",
  },
  {
    id: 11,
    image: "https://picsum.photos/seed/p211/800/800",
    name: "Bluetooth Adapter",
    detail: "USB dongle, plug & play",
    price: 11.99,
    link: "/product/211",
  },
  {
    id: 12,
    image: "https://picsum.photos/seed/p212/800/800",
    name: "Smart LED Bulb",
    detail: "WiFi control, color changing",
    originalPrice: 29.99,
    discountPercent: 30,
    price: 20.99,
    link: "/product/212",
  },
];

export default products2;
