const products = [
  {
    id: 1,
    image: "https://picsum.photos/seed/p1/800/800",
    name: "Wireless Headphones",
    detail: "Noise canceling, comfortable fit",
    originalPrice: 199.99,
    discountPercent: 35,
    price: 129.99,
    link: "/product/1",
  },
  {
    id: 2,
    image: "https://picsum.photos/seed/p2/800/800",
    name: "Smartwatch",
    detail: "Fitness tracking, long battery",
    originalPrice: 249.0,
    discountPercent: 20,
    price: 199.0,
    link: "/product/2",
  },
  {
    id: 3,
    image: "https://picsum.photos/seed/p3/800/800",
    name: "Bluetooth Speaker",
    detail: "Portable, deep bass",
    originalPrice: 79.95,
    discountPercent: 25,
    price: 59.95,
    link: "/product/3",
  },
  {
    id: 4,
    image: "https://picsum.photos/seed/p4/800/800",
    name: "Gaming Mouse",
    detail: "High DPI, RGB lights",
    originalPrice: 59.99,
    discountPercent: 33,
    price: 39.99,
    link: "/product/4",
  },
  {
    id: 5,
    image: "https://picsum.photos/seed/p5/800/800",
    name: "4K Monitor",
    detail: "Ultra HD display",
    originalPrice: 449.0,
    discountPercent: 22,
    price: 349.0,
    link: "/product/5",
  },
  {
    id: 6,
    image: "https://picsum.photos/seed/p6/800/800",
    name: "USB-C Dock",
    detail: "Multiple ports support",
    originalPrice: 99.0,
    discountPercent: 20,
    price: 79.0,
    link: "/product/6",
  },
  {
    id: 7,
    image: "https://picsum.photos/seed/p7/800/800",
    name: "Mechanical Keyboard",
    detail: "Tactile keys, backlight",
    originalPrice: 119.99,
    discountPercent: 25,
    price: 89.99,
    link: "/product/7",
  },
  {
    id: 8,
    image: "https://picsum.photos/seed/p8/800/800",
    name: "Action Camera",
    detail: "4K recording, stabilization",
    originalPrice: 329.5,
    discountPercent: 24,
    price: 249.5,
    link: "/product/8",
  },
  {
    id: 9,
    image: "https://picsum.photos/seed/p9/800/800",
    name: "Portable SSD",
    detail: "Fast external storage",
    originalPrice: 159.99,
    discountPercent: 25,
    price: 119.99,
    link: "/product/9",
  },
  {
    id: 10,
    image: "https://picsum.photos/seed/p10/800/800",
    name: "Wireless Earbuds",
    detail: "Noise canceling, compact",
    originalPrice: 149.99,
    discountPercent: 33,
    price: 99.99,
    link: "/product/10",
  },
];

export default products;
